---

- name: EFS Mount Target
  hosts: shared_efs_client_host
  become: yes
  vars:
      shared_dir_user: nobody
      shared_dir_group: "{{ shared_dir_gid }}"
      shared_dir_groupname: nfs
      shared_dir_name: "{{ efs_shared_mount_dir }}"
      shared_mount_dir: "/mnt/{{ efs_shared_mount_dir }}"
      shared_mount_address: "{{ efs_shared_mount_endpoint }}"
      shared_mount_opts: "{{ efs_shared_mount_options }}"
  tasks:
    - import_tasks: roles/shared_dir/tasks/install.yml
    - import_tasks: roles/shared_dir/tasks/setup_client.yml
  tags:
    - efs_mount_shared_dir
    - nfs

- name: Create purging cron jobs
  hosts: "{{ groups.proxy.0 }}"
  become: yes
  vars:
      shared_mount_dir: "/mnt/{{ efs_shared_mount_dir }}"
      restore_payload_dir_host: "{{ shared_mount_dir }}/restore_payloads"
      transfer_payload_dir_host: "{{ shared_mount_dir }}/transfer_payloads"
      shared_temp_dir_host: "{{ shared_mount_dir }}/temp"
  tasks:
    - import_tasks: roles/shared_dir/tasks/efs_mount_purge_old_files.yml
  tags:
    - efs_purging_temp_cron
    - nfs
